#ifndef RADIOIFY_AUDIOFILTER_RADIO1938_PREVIEW_RADIO_PREVIEW_CONFIG_H
#define RADIOIFY_AUDIOFILTER_RADIO1938_PREVIEW_RADIO_PREVIEW_CONFIG_H

struct RadioPreviewConfig {
  float programBandwidthHz = 2400.0f;
};

#endif  // RADIOIFY_AUDIOFILTER_RADIO1938_PREVIEW_RADIO_PREVIEW_CONFIG_H
