#pragma once

#define RADIOIFY_WIDE_STRING_LITERAL_DETAIL(value) L##value
#define RADIOIFY_WIDE_STRING_LITERAL(value) \
  RADIOIFY_WIDE_STRING_LITERAL_DETAIL(value)

#define RADIOIFY_APP_NAME "Radioify"
#define RADIOIFY_APP_NAME_W RADIOIFY_WIDE_STRING_LITERAL(RADIOIFY_APP_NAME)
#define IDI_RADIOIFY_APP_ICON 101
